version: '3.8'
services:
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  app:
    build: 
      context: node
    container_name: app
    #image: laaferreira/node:latest
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh node index.js
    command: sh -c "npm install && node index.js"
    ports:
      - 3000:3000
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty : true
    depends_on:
      - db
    networks:
      - node-network

 
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
    networks:
      - node-network

networks: 
  node-network:
    driver: bridge     