version: '3.8'
services:
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  app:
    restart: unless-stopped
    container_name: app
    build: 
      context: .
    #image: laaferreira/node:latest
    #entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    ports:
    - 3000:3000
    volumes:
      - ./:/usr/src/app
    tty : true
    depends_on:
      - db
    networks:
      - node-network

 
  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - "8080:8080"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network

networks: 
  node-network:
    driver: bridge     